// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sadec.Api.Data;

#nullable disable

namespace Sadec.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Sadec.Api.Entities.BinhLuan", b =>
                {
                    b.Property<Guid>("MaSo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("NguoiDungId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("TaoLuc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenNguoiGui")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaSo");

                    b.HasIndex("NguoiDungId");

                    b.HasIndex("TargetType", "TargetId");

                    b.ToTable("BinhLuans");
                });

            modelBuilder.Entity("Sadec.Api.Entities.CaiDatHeThong", b =>
                {
                    b.Property<Guid>("MaSo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CapNhatLuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("GiaTri")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Khoa")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("MaSo");

                    b.HasIndex("Khoa")
                        .IsUnique();

                    b.ToTable("CaiDatHeThongs");
                });

            modelBuilder.Entity("Sadec.Api.Entities.DanhMuc", b =>
                {
                    b.Property<Guid>("MaSo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CapNhatLuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DuongDan")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("TaoLuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("MaSo");

                    b.HasIndex("DuongDan")
                        .IsUnique();

                    b.ToTable("DanhMucs");
                });

            modelBuilder.Entity("Sadec.Api.Entities.DiaDiem", b =>
                {
                    b.Property<Guid>("MaSo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AnhDaiDienUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CapNhatLuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DuongDan")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<double?>("KinhDo")
                        .HasColumnType("float");

                    b.Property<int>("LuotXem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("MoTaNgan")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TaoLuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<double?>("ViDo")
                        .HasColumnType("float");

                    b.HasKey("MaSo");

                    b.HasIndex("DuongDan")
                        .IsUnique();

                    b.ToTable("DiaDiems");
                });

            modelBuilder.Entity("Sadec.Api.Entities.DiaDiemDanhMuc", b =>
                {
                    b.Property<Guid>("DiaDiemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DanhMucId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DiaDiemId", "DanhMucId");

                    b.HasIndex("DanhMucId");

                    b.ToTable("DiaDiemDanhMucs");
                });

            modelBuilder.Entity("Sadec.Api.Entities.HoSoDichVu", b =>
                {
                    b.Property<string>("MaHoSo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CapNhatLuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("NgayNopLuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiNop")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TenThuTuc")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaHoSo");

                    b.HasIndex("TrangThai");

                    b.ToTable("HoSoDichVus");
                });

            modelBuilder.Entity("Sadec.Api.Entities.MediaFile", b =>
                {
                    b.Property<Guid>("MaSo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("KichThuocBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("LoaiNoiDung")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("NguoiTaiLenId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("TaoLuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenTep")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("MaSo");

                    b.HasIndex("NguoiTaiLenId");

                    b.ToTable("MediaFiles");
                });

            modelBuilder.Entity("Sadec.Api.Entities.MonAn", b =>
                {
                    b.Property<Guid>("MaSo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AnhDaiDienUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CapNhatLuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DuongDan")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("PhanLoai")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("TaoLuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaSo");

                    b.HasIndex("DuongDan")
                        .IsUnique();

                    b.ToTable("MonAns");
                });

            modelBuilder.Entity("Sadec.Api.Entities.NguoiDung", b =>
                {
                    b.Property<Guid>("MaSo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CapNhatLuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("HoatDongGanNhatLuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("MatKhauHash")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("TaoLuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenHienThi")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaSo");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("NguoiDungs");
                });

            modelBuilder.Entity("Sadec.Api.Entities.ThuTucDichVu", b =>
                {
                    b.Property<Guid>("MaSo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CapNhatLuc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DangHoatDong")
                        .HasColumnType("bit");

                    b.Property<string>("MoTa")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("TaoLuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("MaSo");

                    b.ToTable("ThuTucDichVus");
                });

            modelBuilder.Entity("Sadec.Api.Entities.TinTuc", b =>
                {
                    b.Property<Guid>("MaSo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AnhDaiDienUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CapNhatLuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DuongDan")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("LuotXem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("MoTaNgan")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PhatHanhLuc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("TacGiaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("TaoLuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaSo");

                    b.HasIndex("DuongDan")
                        .IsUnique();

                    b.HasIndex("TacGiaId");

                    b.ToTable("TinTucs");
                });

            modelBuilder.Entity("Sadec.Api.Entities.TinTucDanhMuc", b =>
                {
                    b.Property<Guid>("TinTucId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DanhMucId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TinTucId", "DanhMucId");

                    b.HasIndex("DanhMucId");

                    b.ToTable("TinTucDanhMucs");
                });

            modelBuilder.Entity("Sadec.Api.Entities.BinhLuan", b =>
                {
                    b.HasOne("Sadec.Api.Entities.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("Sadec.Api.Entities.DiaDiemDanhMuc", b =>
                {
                    b.HasOne("Sadec.Api.Entities.DanhMuc", "DanhMuc")
                        .WithMany("DiaDiemDanhMucs")
                        .HasForeignKey("DanhMucId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sadec.Api.Entities.DiaDiem", "DiaDiem")
                        .WithMany("DiaDiemDanhMucs")
                        .HasForeignKey("DiaDiemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DanhMuc");

                    b.Navigation("DiaDiem");
                });

            modelBuilder.Entity("Sadec.Api.Entities.MediaFile", b =>
                {
                    b.HasOne("Sadec.Api.Entities.NguoiDung", "NguoiTaiLen")
                        .WithMany()
                        .HasForeignKey("NguoiTaiLenId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("NguoiTaiLen");
                });

            modelBuilder.Entity("Sadec.Api.Entities.TinTuc", b =>
                {
                    b.HasOne("Sadec.Api.Entities.NguoiDung", "TacGia")
                        .WithMany("TinTucs")
                        .HasForeignKey("TacGiaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("TacGia");
                });

            modelBuilder.Entity("Sadec.Api.Entities.TinTucDanhMuc", b =>
                {
                    b.HasOne("Sadec.Api.Entities.DanhMuc", "DanhMuc")
                        .WithMany("TinTucDanhMucs")
                        .HasForeignKey("DanhMucId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sadec.Api.Entities.TinTuc", "TinTuc")
                        .WithMany("TinTucDanhMucs")
                        .HasForeignKey("TinTucId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DanhMuc");

                    b.Navigation("TinTuc");
                });

            modelBuilder.Entity("Sadec.Api.Entities.DanhMuc", b =>
                {
                    b.Navigation("DiaDiemDanhMucs");

                    b.Navigation("TinTucDanhMucs");
                });

            modelBuilder.Entity("Sadec.Api.Entities.DiaDiem", b =>
                {
                    b.Navigation("DiaDiemDanhMucs");
                });

            modelBuilder.Entity("Sadec.Api.Entities.NguoiDung", b =>
                {
                    b.Navigation("TinTucs");
                });

            modelBuilder.Entity("Sadec.Api.Entities.TinTuc", b =>
                {
                    b.Navigation("TinTucDanhMucs");
                });
#pragma warning restore 612, 618
        }
    }
}
