// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sadec.Api.Data;

#nullable disable

namespace Sadec.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260322074639_KhoiTaoLaiDateTime")]
    partial class KhoiTaoLaiDateTime
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("Sadec.Api.Entities.DiaDiem", b =>
                {
                    b.Property<Guid>("MaSo")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CapNhatLuc");

                    b.Property<string>("DuongDan")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<double?>("KinhDo");

                    b.Property<string>("MoTaNgan")
                        .HasMaxLength(500);

                    b.Property<string>("NoiDung");

                    b.Property<DateTime>("TaoLuc");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<double?>("ViDo");

                    b.HasKey("MaSo");

                    b.HasIndex("DuongDan")
                        .IsUnique();

                    b.ToTable("DiaDiems");
                });

            modelBuilder.Entity("Sadec.Api.Entities.TinTuc", b =>
                {
                    b.Property<Guid>("MaSo")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CapNhatLuc");

                    b.Property<string>("DuongDan")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("MoTaNgan")
                        .HasMaxLength(500);

                    b.Property<string>("NoiDung");

                    b.Property<DateTime?>("PhatHanhLuc");

                    b.Property<DateTime>("TaoLuc");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("MaSo");

                    b.HasIndex("DuongDan")
                        .IsUnique();

                    b.ToTable("TinTucs");
                });
#pragma warning restore 612, 618
        }
    }
}
